/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Roji1.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials["Material.007"]}
        position={[0, 1.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Material.007"]}
        position={[0, 8.09, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002.geometry}
        material={materials["Material.007"]}
        position={[0, 1.1, -1.19]}
        rotation={[0, -0.33, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pipe(air)"].geometry}
        material={materials["Material.002"]}
        position={[-4.86, 3.45, -5.03]}
        scale={[0.1, 3.27, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pipe(air)001"].geometry}
        material={materials["Material.002"]}
        position={[-4.86, 3.45, -5.03]}
        scale={[0.1, 3.27, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pipe(air)002"].geometry}
        material={materials["Material.002"]}
        position={[-4.86, 5.99, -4.47]}
        scale={[0.1, 3.27, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall.geometry}
        material={materials.WAll}
        position={[-5.52, 4.96, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[6.08, 0.56, 6.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.air.geometry}
        material={materials["Material.001"]}
        position={[-4.34, 0.26, -3.13]}
        scale={[0.61, 0.92, 1.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["dansa.001"]}
        position={[5.45, -1.33, 0]}
        scale={[0.46, 0.27, -5.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["WAll.001"]}
        position={[-4.34, -0.85, -2.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.58, 0.58, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["WAll.001"]}
        position={[-4.34, -0.85, -4.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.58, 0.58, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.003"]}
        position={[-4.92, 4.69, -2.38]}
        scale={[0.55, 0.85, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[-4.76, -2.37, 2.95]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.18, -1.13, -0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Material}
        position={[5.78, -2.37, -4.08]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.18, -1.13, -0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Material}
        position={[5.78, -2.37, -3.51]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.18, -1.13, -0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.005"]}
        position={[-4.81, 2.38, 4.53]}
        scale={[0.28, 0.75, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.danball}
        position={[0.74, 0, 0.32]}
        rotation={[0, 0.77, 0]}
        scale={[1.35, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.006"]}
        position={[3.08, 0.42, -4.58]}
        rotation={[0, -0.56, 0]}
        scale={[0.81, 1.27, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.dansa}
        position={[-4.73, -1.33, 0]}
        scale={[1, 0.27, -6.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.008"]}
        position={[-5.03, 2.98, -3.85]}
        scale={[0.28, 0.6, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={materials.Road}
        position={[0, -1.67, 0]}
        scale={[6.08, 0.56, 6.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.manhole}
        position={[2, -1.25, 4.18]}
        scale={[1.12, 0.17, 1.12]}
      />
    </group>
  );
}

useGLTF.preload("/Roji1.gltf");
